<center>
    
    Inverse of Submatrices
    
    Author: Daniel Coble
    
    Status: Finished
</center>

I show an implementation of the method shown in [this](https://stats.stackexchange.com/questions/450146/updating-the-inverse-covariance-matrix-after-deleting-the-i-th-column-and-row-of) stackexchange post, which shows how to use a matix's inverse to calculate the inverse after row and column $i$ are removed.

In [107]:
import numpy as np
'''
_A_inv: inverse of supermatrix
rem_rows: row or rows that are removed to create the submatrix
rem_cols: column or columns that are removed to create the submatrix. Right now the code only works with rem_cols=rem_rows
_A_: supermatrix (not needed but if you pass it, the submatrix A is returned)
'''
def invert_submatrix(_A_inv, rem_rows, rem_cols=None, _A_=None):
    rem_cols = rem_rows
    if(isinstance(rem_rows, int)):
        rem_rows = [rem_rows]
    if(isinstance(rem_cols, int)):
        rem_cols = [rem_cols]
    if(not type(rem_rows) is np.ndarray):
        rem_rows = np.array(rem_rows)
    if(not type(rem_cols) is np.ndarray):
        rem_cols = np.array(rem_cols)
    assert np.size(rem_rows) == np.size(rem_cols)
    k = np.size(rem_rows)
    
    a = _A_inv
    a = np.delete(_A_inv, rem_rows, axis=0)
    a = np.delete(a, rem_cols, axis=1)
    
    b = np.column_stack([_A_inv[:,i] for i in rem_cols])
    c = np.row_stack([_A_inv[[i],:] for i in rem_rows])
    d = np.row_stack([b[i,:] for i in rem_rows])
    b = np.delete(b, rem_rows, axis=0)
    c = np.delete(c, rem_cols, axis=1)
    
    return a - b@np.linalg.inv(d)@c

In [109]:
_A_ = np.random.rand(5, 5)
_A_inv = np.linalg.inv(_A_)
rem_rows = [1]

A = np.delete(np.delete(_A_, 1, axis=0), 1, axis=1)
A_inv = np.linalg.inv(A)

assert np.allclose(A_inv, invert_submatrix(_A_inv, rem_rows))

In [22]:
import numpy as np
def invert_submatrix(_A_inv, rem_rows, rem_cols=None, _A_=None):
    if(isinstance(rem_rows, int)):
        rem_rows = [rem_rows]
    if(isinstance(rem_cols, int)):
        rem_cols = [rem_cols]
    if(not type(rem_rows) is np.ndarray):
        rem_rows = np.array(rem_rows)
    if(not type(rem_cols) is np.ndarray):
        rem_cols = np.array(rem_cols)
    assert np.size(rem_rows) == np.size(rem_cols)
    k = np.size(rem_rows)
    
    A = None
    if(not _A_ is None):
        A = np.delete(_A_, rem_rows, axis=0)
        A = np.delete(A, rem_cols, axis=1)
    
    a = _A_inv
    a = np.delete(_A_inv, rem_rows, axis=0)
    a = np.delete(a, rem_cols, axis=1)
    
    b = np.column_stack([_A_inv[:,i] for i in rem_cols])
    c = np.row_stack([_A_inv[[i],:] for i in rem_rows])
    d = np.row_stack([b[i,:] for i in rem_rows])
    b = np.delete(b, rem_rows, axis=0)
    c = np.delete(c, rem_cols, axis=1)
    
    Ainv = a - b@np.linalg.inv(d)@c
    if(not A is None):
        return (Ainv, A)
    return Ainv


_A_ = np.random.rand(5, 5)
_A_inv = np.linalg.inv(_A_)
rem_rows = [1]
rem_cols = [2]

Ainv, A = invert_submatrix(_A_inv, rem_rows, rem_cols, _A_)

In [23]:
Ainv

array([[-2.61222745,  3.88601845, -1.18444947,  0.19935649],
       [ 1.33791441, -1.39195135, -2.43648608,  0.94505613],
       [ 2.68920853, -1.07827884, -2.11734837, -0.61828273],
       [ 0.72321397, -2.61101662,  4.80492123,  0.03097552]])

In [24]:
np.linalg.inv(A)

array([[-4.86394674,  5.88105885, -3.36064609,  1.90552609],
       [-1.41460189,  1.3895984 ,  1.09303199, -0.22026765],
       [ 0.28441929,  1.34418393,  0.82739191, -1.56344191],
       [ 6.95074749, -8.58275559,  2.62423756, -0.38128943]])

In [12]:
A

array([[0.96020603, 0.88692717, 0.10210345, 0.4752087 ],
       [0.6017152 , 0.85413868, 0.27695666, 0.24717578],
       [0.05723689, 0.42407753, 0.96334846, 0.85806172],
       [0.07703119, 0.37504911, 0.41835966, 0.52561045]])

In [13]:
_A_

array([[9.60206026e-01, 8.86927167e-01, 8.15334157e-01, 1.02103451e-01,
        4.75208696e-01],
       [3.38630415e-02, 5.86541892e-02, 6.32349610e-01, 5.52853053e-01,
        1.90989900e-01],
       [6.01715200e-01, 8.54138681e-01, 7.78135662e-04, 2.76956661e-01,
        2.47175780e-01],
       [5.72368907e-02, 4.24077534e-01, 6.88933200e-01, 9.63348464e-01,
        8.58061724e-01],
       [7.70311886e-02, 3.75049115e-01, 9.75932703e-01, 4.18359661e-01,
        5.25610450e-01]])

In [19]:
A@Ainv

array([[ 1.00000000e+00, -4.44089210e-16,  1.11022302e-16,
         0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00, -1.77635684e-15,  1.00000000e+00,
         0.00000000e+00],
       [-8.88178420e-16, -8.88178420e-16,  0.00000000e+00,
         1.00000000e+00]])